
import { Department, Tool } from './types';

export const INITIAL_TOOLS: Tool[] = [
  {
    id: 'tool_0',
    department: Department.CONCRETE,
    category: '운영관리',
    tool_name: '아임웹(숏폼,상세페이지,쿠팡)',
    description: '숏폼 랜딩페이지, 상세페이지, 쿠팡 연동 웹사이트 제작 플랫폼',
    logoUrl: 'https://www.google.com/s2/favicons?domain=imweb.me&sz=128',
    manual_link: '',
    service_url: 'https://imweb.me',
    login_id: 'support@samchomaeul.com (구글 연동)',
    login_pw: 'Tkach323#@# (첫 문자 대문자 주의)',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 0
  },
  {
    id: 'tool_1',
    department: Department.CONCRETE,
    category: '운영관리',
    tool_name: '아임웹(마케팅사업부)',
    description: '마케팅사업부 전용 웹사이트 제작 및 관리 플랫폼',
    logoUrl: 'https://www.google.com/s2/favicons?domain=imweb.me&sz=128',
    manual_link: '',
    service_url: 'https://imweb.me',
    login_id: 'support@mkm20201101.com (구글 연동)',
    login_pw: 'Moment1!',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 1
  },
  {
    id: 'tool_2',
    department: Department.CONCRETE,
    category: '운영관리',
    tool_name: 'ccfm (워드프레스)',
    description: '워드프레스 기반 웹사이트 및 블로그 운영 플랫폼',
    logoUrl: 'https://www.google.com/s2/favicons?domain=ccfm.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://ccfm.co.kr/wp-admin/admin.php?page=chromeapp-helper-banner',
    login_id: 'chungchoegg',
    login_pw: 'tkach1212!',
    memo: 'API: wRTc jGnQ 7SII V5h6 2sDA 76S4',
    in_use: 'Y',
    is_paid: 'Y',
    order: 2
  },
  {
    id: 'tool_3',
    department: Department.CONCRETE,
    category: '데이터분석',
    tool_name: '뷰저블(자사)',
    description: '히트맵, 스크롤맵 등 사용자 행동 분석 UX 애널리틱스 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.beusable.net&sz=128',
    manual_link: '',
    service_url: 'https://www.beusable.net',
    login_id: 'ccfmedu@ccfm.co.kr',
    login_pw: 'Moment1!',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 3
  },
  {
    id: 'tool_4',
    department: Department.CONCRETE,
    category: '생산성',
    tool_name: '탈리',
    description: '간편한 온라인 설문조사 및 폼 빌더',
    logoUrl: 'https://www.google.com/s2/favicons?domain=tally.so&sz=128',
    manual_link: '',
    service_url: 'https://tally.so',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 4
  },
  {
    id: 'tool_5',
    department: Department.CONCRETE,
    category: '비디오AI',
    tool_name: '캡컷(Capcut)',
    description: 'AI 기반 숏폼 영상 편집 및 자동 자막 생성 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.capcut.com&sz=128',
    manual_link: '',
    service_url: 'https://www.capcut.com',
    login_id: 'ccfmbrandmkt@gmail.com(구글 연동)',
    login_pw: 'qmaktlf12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 5
  },
  {
    id: 'tool_6',
    department: Department.CONCRETE,
    category: '운영관리',
    tool_name: '솔라피',
    description: '문자, 알림톡, 친구톡 대량 발송 메시징 서비스',
    logoUrl: 'https://www.google.com/s2/favicons?domain=solapi.com&sz=128',
    manual_link: '',
    service_url: 'https://solapi.com',
    login_id: 'admin@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '2단계 인증비번: 123456',
    in_use: 'Y',
    is_paid: 'Y',
    order: 6
  },
  {
    id: 'tool_7',
    department: Department.CONCRETE,
    category: '협업',
    tool_name: '줌(zoom)',
    description: '화상회의 및 웨비나 진행 플랫폼',
    logoUrl: 'https://www.google.com/s2/favicons?domain=zoom.us&sz=128',
    manual_link: '',
    service_url: 'https://zoom.us',
    login_id: 'ccfmedu@ccfm.co.kr',
    login_pw: 'Ahajsxm12!@',
    memo: '소셜로그인도 가능',
    in_use: 'Y',
    is_paid: 'Y',
    order: 7
  },
  {
    id: 'tool_8',
    department: Department.CONCRETE,
    category: '생산성 AI',
    tool_name: '클로드 Max 플랜',
    description: 'Anthropic의 고급 AI 어시스턴트 구독 서비스',
    logoUrl: 'https://www.google.com/s2/favicons?domain=claude.ai&sz=128',
    manual_link: '',
    service_url: 'https://claude.ai',
    login_id: 'ccfmbrandmkt@gmail.com',
    login_pw: 'tkach212@!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 8
  },
  {
    id: 'tool_9',
    department: Department.CONCRETE,
    category: '생산성 AI',
    tool_name: 'Make 노코드 툴',
    description: '앱 간 워크플로우 자동화 노코드 플랫폼',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.make.com&sz=128',
    manual_link: '',
    service_url: 'https://www.make.com',
    login_id: 'ai@ccfm.co.kr',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 9
  },
  {
    id: 'tool_10',
    department: Department.CONCRETE,
    category: '운영관리',
    tool_name: '아웃코드',
    description: '국내 SaaS 연동 특화 업무 자동화 노코드 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=outcode.biz&sz=128',
    manual_link: '',
    service_url: 'https://outcode.biz',
    login_id: 'ccfmbrandmkt@gmail.com',
    login_pw: 'qmaktlf12!@(지메일연동)',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 10
  },
  {
    id: 'tool_11',
    department: Department.CONCRETE,
    category: '데이터분석',
    tool_name: '블랙키위',
    description: '네이버 키워드 검색량 및 경쟁도 분석 SEO 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=blackkiwi.net&sz=128',
    manual_link: '',
    service_url: 'https://blackkiwi.net',
    login_id: 'support@mkm20201101.com',
    login_pw: '모먼트12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 11
  },
  {
    id: 'tool_12',
    department: Department.CONCRETE,
    category: '디자인',
    tool_name: '망고보드',
    description: '템플릿 기반 카드뉴스, 썸네일, SNS 콘텐츠 디자인 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.mangoboard.net&sz=128',
    manual_link: '',
    service_url: 'https://www.mangoboard.net',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 12
  },
  {
    id: 'tool_13',
    department: Department.CONCRETE,
    category: '운영관리',
    tool_name: '모두싸인',
    description: '온라인 전자계약 및 문서 서명 서비스',
    logoUrl: 'https://www.google.com/s2/favicons?domain=modusign.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://modusign.co.kr',
    login_id: 'admin@ccfm.co.kr',
    login_pw: 'ahenTkdls12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 13
  },
  {
    id: 'tool_14',
    department: Department.CONCRETE,
    category: '데이터분석',
    tool_name: '썸트렌드',
    description: '소셜 빅데이터 기반 트렌드 및 키워드 분석 플랫폼',
    logoUrl: 'https://www.google.com/s2/favicons?domain=some.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://some.co.kr',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '소셜로그인 구글',
    in_use: 'Y',
    is_paid: 'Y',
    order: 14
  },
  {
    id: 'tool_15',
    department: Department.CONCRETE,
    category: '인사이트',
    tool_name: '퍼블리 계정',
    description: '비즈니스 인사이트 및 실무 콘텐츠 구독 서비스',
    logoUrl: 'https://www.google.com/s2/favicons?domain=publy.co&sz=128',
    manual_link: '',
    service_url: 'https://publy.co',
    login_id: 'admin@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 15
  },
  {
    id: 'tool_16',
    department: Department.CONCRETE,
    category: '운영관리',
    tool_name: '가비아(ccfmedu도메인)',
    description: 'ccfmedu 도메인 등록 및 호스팅 관리 서비스',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.gabia.com&sz=128',
    manual_link: '',
    service_url: 'https://www.gabia.com',
    login_id: 'ccfmedu@ccfm.co.kr',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 16
  },
  {
    id: 'tool_17',
    department: Department.CONCRETE,
    category: '미디어 소스',
    tool_name: 'artlist',
    description: '로열티프리 음원, 효과음, 영상 클립 소스 구독 서비스',
    logoUrl: 'https://www.google.com/s2/favicons?domain=artlist.io&sz=128',
    manual_link: '',
    service_url: 'https://artlist.io',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 17
  },
  {
    id: 'tool_18',
    department: Department.CONCRETE,
    category: '일반',
    tool_name: '스티비',
    description: '급상승 뉴스레터 발송을 위한 스티비 결제 (스탠다드 요금제)',
    logoUrl: 'https://www.google.com/s2/favicons?domain=stibee.com&sz=128',
    manual_link: '',
    service_url: 'https://stibee.com/',
    login_id: 'ccfmbrandmkt@gmail.com',
    login_pw: 'qmaktlf12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 18
  },
  {
    id: 'tool_19',
    department: Department.CONCRETE,
    category: 'AI',
    tool_name: '젠스파크',
    description: 'AI 슬라이드, 시트 기능',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.genspark.ai&sz=128',
    manual_link: '',
    service_url: 'https://www.genspark.ai/',
    login_id: 'ccfmbrandmkt@gmail.com',
    login_pw: 'qmaktlf12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 19
  },
  {
    id: 'tool_20',
    department: Department.BRAND,
    category: '생산성 AI',
    tool_name: 'Chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com',
    login_id: 'ccfmbrand@gmail.com',
    login_pw: 'qmfosemtkdjqqn12#',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 20
  },
  {
    id: 'tool_21',
    department: Department.BRAND,
    category: '비디오AI',
    tool_name: 'Runway',
    description: 'AI 영상 제작 및 편집',
    logoUrl: 'https://www.google.com/s2/favicons?domain=runwayml.com&sz=128',
    manual_link: '',
    service_url: 'https://runwayml.com',
    login_id: 'ccfmbrand@gmail.com',
    login_pw: 'qmfosemtkdjqqn12#',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 21
  },
  {
    id: 'tool_22',
    department: Department.BRAND,
    category: '생산성 AI',
    tool_name: '클로드',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=claude.ai&sz=128',
    manual_link: '',
    service_url: 'https://claude.ai',
    login_id: 'ccfmbrand@gmail.com',
    login_pw: 'qmfosemtkdjqqn12#',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 22
  },
  {
    id: 'tool_23',
    department: Department.BRAND,
    category: '비디오AI',
    tool_name: 'Akool',
    description: '딥페이크 소스 활용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=akool.com&sz=128',
    manual_link: '',
    service_url: 'https://akool.com',
    login_id: 'ccfmbrand@gmail.com',
    login_pw: 'qmfosemtkdjqqn12#',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 23
  },
  {
    id: 'tool_24',
    department: Department.BRAND,
    category: '비디오AI',
    tool_name: '탑뷰',
    description: 'AI 비디오 편집',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.topview.ai&sz=128',
    manual_link: '',
    service_url: 'https://www.topview.ai',
    login_id: 'ccfmbrand@gmail.com',
    login_pw: 'qmfosemtkdjqqn12#',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 24
  },
  {
    id: 'tool_25',
    department: Department.BRAND,
    category: '비디오AI',
    tool_name: '구글 플로우',
    description: '브랜드사업부 Veo3 활용을 통한 콘텐츠 소스 생성',
    logoUrl: 'https://www.google.com/s2/favicons?domain=aistudio.google.com&sz=128',
    manual_link: '',
    service_url: 'https://aistudio.google.com/models/veo-3',
    login_id: 'ccfm0020@gmail.com',
    login_pw: 'zhszm123$',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 25
  },
  {
    id: 'tool_26',
    department: Department.MARKETING,
    category: '일반',
    tool_name: '카페24',
    description: '어드민 호스팅 서비스',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.cafe24.com&sz=128',
    manual_link: '',
    service_url: 'https://www.cafe24.com/',
    login_id: 'ccfmacademy',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 26
  },
  {
    id: 'tool_27',
    department: Department.MARKETING,
    category: '미디어 소스',
    tool_name: 'artlist',
    description: '음향효과',
    logoUrl: 'https://www.google.com/s2/favicons?domain=artlist.io&sz=128',
    manual_link: '',
    service_url: 'https://artlist.io/',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 27
  },
  {
    id: 'tool_28',
    department: Department.MARKETING,
    category: '미디어 소스',
    tool_name: '셔터스톡',
    description: '음향효과 및 사진 컨텐츠 참고',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.shutterstock.com&sz=128',
    manual_link: '',
    service_url: 'https://www.shutterstock.com/ko/',
    login_id: 'mkm506413@gmail.com',
    login_pw: 'mkmahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 28
  },
  {
    id: 'tool_29',
    department: Department.MARKETING,
    category: '미디어 소스',
    tool_name: '타입캐스트',
    description: '비디오 콘텐츠 활용 (음성다운)',
    logoUrl: 'https://www.google.com/s2/favicons?domain=typecast.ai&sz=128',
    manual_link: '',
    service_url: 'https://typecast.ai/kr',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 29
  },
  {
    id: 'tool_30',
    department: Department.MARKETING,
    category: '비디오AI',
    tool_name: 'elevenlabs',
    description: 'AI더빙',
    logoUrl: 'https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=128',
    manual_link: '',
    service_url: 'https://elevenlabs.io/',
    login_id: 'admin@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 30
  },
  {
    id: 'tool_31',
    department: Department.MARKETING,
    category: '생산성',
    tool_name: 'MAKE',
    description: '업무 자동화를 위한 솔루션 도입',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.make.com&sz=128',
    manual_link: '',
    service_url: 'https://www.make.com/en/ai-automation',
    login_id: 'ai@ccfm.co.kr',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 31
  },
  {
    id: 'tool_32',
    department: Department.MARKETING,
    category: '생산성',
    tool_name: '탈리',
    description: '셀캠 고객사 DB수집을 위한 "탈리" 업무툴 월 구독료 결제 요청',
    logoUrl: 'https://www.google.com/s2/favicons?domain=tali.ai&sz=128',
    manual_link: '',
    service_url: 'https://tali.ai/',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 32
  },
  {
    id: 'tool_33',
    department: Department.MARKETING,
    category: '운영관리',
    tool_name: '아임웹',
    description: '마케팅사업부 DB 확보',
    logoUrl: 'https://www.google.com/s2/favicons?domain=imweb.me&sz=128',
    manual_link: '',
    service_url: 'https://imweb.me/',
    login_id: 'admin@mkm20201101.com',
    login_pw: 'Ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 33
  },
  {
    id: 'tool_34',
    department: Department.MARKETING,
    category: '데이터분석',
    tool_name: '블랙키위',
    description: '키워드 검색량 조회 및 분석',
    logoUrl: 'https://www.google.com/s2/favicons?domain=blackkiwi.net&sz=128',
    manual_link: '',
    service_url: 'https://blackkiwi.net/',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 34
  },
  {
    id: 'tool_35',
    department: Department.MARKETING,
    category: '데이터분석',
    tool_name: '썸트렌드',
    description: '소셜 언급량 분석',
    logoUrl: 'https://www.google.com/s2/favicons?domain=some.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://some.co.kr/',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 35
  },
  {
    id: 'tool_36',
    department: Department.MARKETING,
    category: '데이터분석',
    tool_name: '씨그로 대시보드 정기결제',
    description: '광고주 데이터 자동화 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.cigro.io&sz=128',
    manual_link: '',
    service_url: 'https://www.cigro.io/',
    login_id: 'mkm506413@gmail.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 36
  },
  {
    id: 'tool_37',
    department: Department.MARKETING,
    category: '디자인',
    tool_name: '망고보드',
    description: '확인 필요',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.mangoboard.net&sz=128',
    manual_link: '',
    service_url: 'https://www.mangoboard.net/',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 37
  },
  {
    id: 'tool_38',
    department: Department.MARKETING,
    category: '인사이트',
    tool_name: '퍼블리',
    description: '마케팅전략 및 콘텐츠 제공',
    logoUrl: 'https://www.google.com/s2/favicons?domain=publy.co&sz=128',
    manual_link: '',
    service_url: 'https://publy.co/',
    login_id: 'admin@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 38
  },
  {
    id: 'tool_39',
    department: Department.MARKETING,
    category: '디자인',
    tool_name: '클립아트코리아',
    description: '라이선스, 이미지 다운',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.clipartkorea.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://www.clipartkorea.co.kr/',
    login_id: 'mkm202011',
    login_pw: 'mkmahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 39
  },
  {
    id: 'tool_40',
    department: Department.MARKETING,
    category: '디자인',
    tool_name: '유토이미지',
    description: '유료 이미지,컨텐츠 다운',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.utoimage.com&sz=128',
    manual_link: '',
    service_url: 'https://www.utoimage.com/',
    login_id: 'mkm20201101',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 40
  },
  {
    id: 'tool_41',
    department: Department.MARKETING,
    category: '디자인',
    tool_name: '릭스폰트',
    description: '유료 폰트 사용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.rixfontcloud.com&sz=128',
    manual_link: '',
    service_url: 'https://www.rixfontcloud.com/',
    login_id: 'mkm506413@gmail.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 41
  },
  {
    id: 'tool_42',
    department: Department.MARKETING,
    category: '디자인',
    tool_name: 'Ideogram AI',
    description: '이미지 생성형 AI툴 신규 결제',
    logoUrl: 'https://www.google.com/s2/favicons?domain=ideogram.ai&sz=128',
    manual_link: '',
    service_url: 'https://ideogram.ai',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 42
  },
  {
    id: 'tool_43',
    department: Department.MARKETING,
    category: '검색광고',
    tool_name: '스마트로그',
    description: '검색광고팀 자동입찰 프로그램',
    logoUrl: 'https://www.google.com/s2/favicons?domain=smlog.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://smlog.co.kr',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 43
  },
  {
    id: 'tool_44',
    department: Department.MARKETING,
    category: '디자인',
    tool_name: '망고보드',
    description: '디자인 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.mangoboard.net&sz=128',
    manual_link: '',
    service_url: 'https://www.mangoboard.net/',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 44
  },
  {
    id: 'tool_45',
    department: Department.MARKETING,
    category: '디자인',
    tool_name: '미드저니',
    description: 'ai이미지생성',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.midjourney.com&sz=128',
    manual_link: '',
    service_url: 'https://www.midjourney.com/home',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 45
  },
  {
    id: 'tool_46',
    department: Department.MARKETING,
    category: '디자인',
    tool_name: '미드저니',
    description: 'ai이미지생성',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.midjourney.com&sz=128',
    manual_link: '',
    service_url: 'https://www.midjourney.com/home',
    login_id: 'admin@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 46
  },
  {
    id: 'tool_47',
    department: Department.MARKETING,
    category: '운영관리',
    tool_name: '아마존',
    description: '이사님 사용 목적',
    logoUrl: 'https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=128',
    manual_link: '',
    service_url: 'https://aws.amazon.com/ko/',
    login_id: 'mkm506413@gmail.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 47
  },
  {
    id: 'tool_48',
    department: Department.MARKETING,
    category: '생산성 AI',
    tool_name: 'chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com/',
    login_id: 'ccfmDA1@gmail.com',
    login_pw: 'zhszmflxm123$',
    memo: '생성자: 동재원 (생성자 2차 인증 필요)',
    in_use: 'Y',
    is_paid: 'Y',
    order: 48
  },
  {
    id: 'tool_49',
    department: Department.MARKETING,
    category: '생산성 AI',
    tool_name: 'chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com/',
    login_id: 'ccfmDA2@gmail.com',
    login_pw: 'zhszmflxm123$',
    memo: '생성자: 민길상 (생성자 2차 인증 필요)',
    in_use: 'Y',
    is_paid: 'Y',
    order: 49
  },
  {
    id: 'tool_50',
    department: Department.MARKETING,
    category: '생산성 AI',
    tool_name: 'chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com/',
    login_id: 'ccfmDA3@gmail.com',
    login_pw: 'zhszmflxm123$',
    memo: '생성자: 전승탁 (생성자 2차 인증 필요)',
    in_use: 'Y',
    is_paid: 'Y',
    order: 50
  },
  {
    id: 'tool_51',
    department: Department.MARKETING,
    category: '생산성 AI',
    tool_name: 'chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com/',
    login_id: 'ccfmDA4@gmail.com',
    login_pw: 'zhszmflxm123$',
    memo: '생성자: 윤신혁 (생성자 2차 인증 필요)',
    in_use: 'Y',
    is_paid: 'Y',
    order: 51
  },
  {
    id: 'tool_52',
    department: Department.MARKETING,
    category: '생산성 AI',
    tool_name: 'chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com/',
    login_id: 'ccfmda2.2@gmail.com',
    login_pw: 'zhszmflxm123$',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 52
  },
  {
    id: 'tool_53',
    department: Department.MARKETING,
    category: '생산성 AI',
    tool_name: 'chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com/',
    login_id: 'ccfmGG1@gmail.com',
    login_pw: 'zhszmflxm123$',
    memo: '생성자: 김강휘 (생성자 2차 인증 필요)',
    in_use: 'Y',
    is_paid: 'Y',
    order: 53
  },
  {
    id: 'tool_54',
    department: Department.MARKETING,
    category: '생산성 AI',
    tool_name: 'chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com/',
    login_id: 'ccfmGG1.1@gmail.com',
    login_pw: 'zhszmflxm123$$',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 54
  },
  {
    id: 'tool_55',
    department: Department.MARKETING,
    category: '생산성 AI',
    tool_name: 'chat GPT',
    description: '생산형 AI 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=128',
    manual_link: '',
    service_url: 'https://chat.openai.com/',
    login_id: 'ccfmDA1.1@gmail.com',
    login_pw: 'zhszmflxm123$',
    memo: '생성자: 동재원 (생성자 2차 인증 필요)',
    in_use: 'Y',
    is_paid: 'Y',
    order: 55
  },
  {
    id: 'tool_56',
    department: Department.MARKETING,
    category: '운영관리',
    tool_name: '쿠팡',
    description: '사무용품 구매',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.coupang.com&sz=128',
    manual_link: '',
    service_url: 'https://www.coupang.com/',
    login_id: 'admin@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '쿠팡 와우 계정',
    in_use: 'Y',
    is_paid: 'Y',
    order: 56
  },
  {
    id: 'tool_57',
    department: Department.MARKETING,
    category: '검색광고',
    tool_name: '아이템스카우트',
    description: '검색광고팀 쇼핑검새광고 카테고리 추가 및 연관키워드 분석',
    logoUrl: 'https://www.google.com/s2/favicons?domain=itemscout.io&sz=128',
    manual_link: '',
    service_url: 'https://itemscout.io',
    login_id: 'mine5327@naver.com',
    login_pw: 'fZ!D7VAuVJ#u#.',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 57
  },
  {
    id: 'tool_58',
    department: Department.MARKETING,
    category: '비디오AI',
    tool_name: 'AKOOL',
    description: '딥페이크 소스 활용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=akool.com&sz=128',
    manual_link: '',
    service_url: 'https://akool.com/ko-kr',
    login_id: 'mkm1101m@gmail.com',
    login_pw: 'dudtkdxla12',
    memo: '영상팀 계정 / 윤지민CD 2차 인증 필요',
    in_use: 'Y',
    is_paid: 'Y',
    order: 58
  },
  {
    id: 'tool_59',
    department: Department.MARKETING,
    category: '비디오AI',
    tool_name: '구글 울트라',
    description: 'VEO3 활용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=google.com&sz=128',
    manual_link: '',
    service_url: '',
    login_id: 'mkm.ai.20201101@gmail.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 59
  },
  {
    id: 'tool_60',
    department: Department.MARKETING,
    category: '비디오AI',
    tool_name: 'KLINGAI',
    description: '생성형 ai 툴 도입을 위한 생산성 증진',
    logoUrl: 'https://www.google.com/s2/favicons?domain=app.klingai.com&sz=128',
    manual_link: '',
    service_url: 'https://app.klingai.com/',
    login_id: 'mkm1101m@gmail.com',
    login_pw: 'dudtkdxla12',
    memo: '영상팀 계정 / 윤지민CD 2차 인증 필요',
    in_use: 'Y',
    is_paid: 'Y',
    order: 60
  },
  {
    id: 'tool_61',
    department: Department.MARKETING,
    category: '비디오AI',
    tool_name: 'TOPVIEW',
    description: 'AI 동영상 생성',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.topview.ai&sz=128',
    manual_link: '',
    service_url: 'https://www.topview.ai/ko',
    login_id: 'mkm1101m@gmail.com',
    login_pw: 'dudtkdxla12',
    memo: '영상팀 계정 / 윤지민CD 2차 인증 필요',
    in_use: 'Y',
    is_paid: 'Y',
    order: 61
  },
  {
    id: 'tool_62',
    department: Department.MARKETING,
    category: '운영관리',
    tool_name: '가비아',
    description: 'MKM 웹 호스팅 유지비용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.gabia.com&sz=128',
    manual_link: '',
    service_url: 'https://www.gabia.com/',
    login_id: 'mkm506413@gmail.com',
    login_pw: '구글 계정으로 로그인',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 62
  },
  {
    id: 'tool_63',
    department: Department.MARKETING,
    category: '생산성',
    tool_name: '버블',
    description: 'GFA 자동입찰 프로그램 서버비',
    logoUrl: 'https://www.google.com/s2/favicons?domain=bubble.io&sz=128',
    manual_link: '',
    service_url: 'https://bubble.io',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 63
  },
  {
    id: 'tool_64',
    department: Department.MARKETING,
    category: '비디오AI',
    tool_name: 'Higgsfield',
    description: 'ai 이미지, 영상 생성',
    logoUrl: 'https://www.google.com/s2/favicons?domain=higgsfield.ai&sz=128',
    manual_link: '',
    service_url: 'https://higgsfield.ai/',
    login_id: 'mkm1101m@gmail.com',
    login_pw: 'dudtkdxla12',
    memo: '영상팀 계정 / 윤지민CD 2차 인증 필요',
    in_use: 'Y',
    is_paid: 'Y',
    order: 64
  },
  {
    id: 'tool_65',
    department: Department.MARKETING,
    category: '비디오AI',
    tool_name: '웨이브덱',
    description: 'AI 음성/영상',
    logoUrl: 'https://www.google.com/s2/favicons?domain=wavedeck.ai&sz=128',
    manual_link: '',
    service_url: 'https://wavedeck.ai/',
    login_id: 'mkm1101m@gmail.com',
    login_pw: 'dudtkdxla12',
    memo: '영상팀 계정 / 윤지민CD 2차 인증 필요',
    in_use: 'Y',
    is_paid: 'Y',
    order: 65
  },
  {
    id: 'tool_66',
    department: Department.MARKETING,
    category: '협업',
    tool_name: 'loom',
    description: '마케팅사업부 교육용 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.loom.com&sz=128',
    manual_link: '',
    service_url: 'https://www.loom.com/pricing',
    login_id: 'support@mkm20201101.com',
    login_pw: 'ahajsxm12!@',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 66
  },
  {
    id: 'tool_67',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: 'Adobe',
    description: '포토샵',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.adobe.com&sz=128',
    manual_link: '',
    service_url: 'https://www.adobe.com/kr/?sdid=2NVQC8BX&mv=search&mv2=CC|Naver|BrandSearch&s_kwcid=AL!3085!87!6a95ae9d099d44adfd8b48b0b7f72068&ef_id=Xb98tgAAADZ5zHNU:20220210064955:s',
    login_id: 'pyr@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 67
  },
  {
    id: 'tool_68',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: 'Adobe',
    description: '포토샵',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.adobe.com&sz=128',
    manual_link: '',
    service_url: 'https://www.adobe.com/kr/?sdid=2NVQC8BX&mv=search&mv2=CC|Naver|BrandSearch&s_kwcid=AL!3085!87!6a95ae9d099d44adfd8b48b0b7f72068&ef_id=Xb98tgAAADZ5zHNU:20220210064955:s',
    login_id: 'bec@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 68
  },
  {
    id: 'tool_69',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: 'Adobe',
    description: '프리미어',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.adobe.com&sz=128',
    manual_link: '',
    service_url: 'https://www.adobe.com/kr/?sdid=2NVQC8BX&mv=search&mv2=CC|Naver|BrandSearch&s_kwcid=AL!3085!87!6a95ae9d099d44adfd8b48b0b7f72068&ef_id=Xb98tgAAADZ5zHNU:20220210064955:s',
    login_id: 'eggchungcho@gmail.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 69
  },
  {
    id: 'tool_70',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: 'Adobe',
    description: '프리미어',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.adobe.com&sz=128',
    manual_link: '',
    service_url: 'https://www.adobe.com/kr/?sdid=2NVQC8BX&mv=search&mv2=CC|Naver|BrandSearch&s_kwcid=AL!3085!87!6a95ae9d099d44adfd8b48b0b7f72068&ef_id=Xb98tgAAADZ5zHNU:20220210064955:s',
    login_id: 'ccfmshortform@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 70
  },
  {
    id: 'tool_71',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: 'Adobe',
    description: '프리미어',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.adobe.com&sz=128',
    manual_link: '',
    service_url: 'https://www.adobe.com/kr/?sdid=2NVQC8BX&mv=search&mv2=CC|Naver|BrandSearch&s_kwcid=AL!3085!87!6a95ae9d099d44adfd8b48b0b7f72068&ef_id=Xb98tgAAADZ5zHNU:20220210064955:s',
    login_id: 'nkr@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 71
  },
  {
    id: 'tool_72',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: 'Adobe',
    description: '프리미어',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.adobe.com&sz=128',
    manual_link: '',
    service_url: 'https://www.adobe.com/kr/?sdid=2NVQC8BX&mv=search&mv2=CC|Naver|BrandSearch&s_kwcid=AL!3085!87!6a95ae9d099d44adfd8b48b0b7f72068&ef_id=Xb98tgAAADZ5zHNU:20220210064955:s',
    login_id: 'cs@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 72
  },
  {
    id: 'tool_73',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: 'Adobe',
    description: '포토샵 - 간단 수정용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.adobe.com&sz=128',
    manual_link: '',
    service_url: 'https://www.adobe.com/kr/?sdid=2NVQC8BX&mv=search&mv2=CC|Naver|BrandSearch&s_kwcid=AL!3085!87!6a95ae9d099d44adfd8b48b0b7f72068&ef_id=Xb98tgAAADZ5zHNU:20220210064955:s',
    login_id: 'support@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 73
  },
  {
    id: 'tool_74',
    department: Department.DISTRIBUTION,
    category: '협업',
    tool_name: 'ChatGPT',
    description: '숏폼, 디자인, 유통 사용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chatgpt.com&sz=128',
    manual_link: '',
    service_url: 'https://chatgpt.com/',
    login_id: 'support@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 74
  },
  {
    id: 'tool_75',
    department: Department.DISTRIBUTION,
    category: '생산성 AI',
    tool_name: 'ChatGPT',
    description: '경영관리실 전용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=chatgpt.com&sz=128',
    manual_link: '',
    service_url: 'https://chatgpt.com/',
    login_id: 'tax@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 75
  },
  {
    id: 'tool_76',
    department: Department.DISTRIBUTION,
    category: '생산성 AI',
    tool_name: '데이터라이즈',
    description: '수무수 쇼핑몰 DB 분석',
    logoUrl: 'https://www.google.com/s2/favicons?domain=datarize.ai&sz=128',
    manual_link: '',
    service_url: 'https://datarize.ai/ko',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 76
  },
  {
    id: 'tool_77',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: '리핏',
    description: '사이트별 광고비 사용 내역 통합 조회',
    logoUrl: 'https://www.google.com/s2/favicons?domain=google.com&sz=128',
    manual_link: '',
    service_url: '',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 77
  },
  {
    id: 'tool_78',
    department: Department.DISTRIBUTION,
    category: '비디오 AI',
    tool_name: '미드저니',
    description: 'AI 이미지 생성 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.midjourney.com&sz=128',
    manual_link: '',
    service_url: 'https://www.midjourney.com',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 78
  },
  {
    id: 'tool_79',
    department: Department.DISTRIBUTION,
    category: '음성 AI',
    tool_name: '타입캐스트',
    description: '음성 AI서비스',
    logoUrl: 'https://www.google.com/s2/favicons?domain=typecast.ai&sz=128',
    manual_link: '',
    service_url: 'https://typecast.ai',
    login_id: 'ccfmshortform@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 79
  },
  {
    id: 'tool_80',
    department: Department.DISTRIBUTION,
    category: '텍스트',
    tool_name: '산돌구름',
    description: '숏폼, 디자인 유료폰트 사용',
    logoUrl: 'https://www.google.com/s2/favicons?domain=cloud.sandoll.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://cloud.sandoll.co.kr',
    login_id: 'design@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 80
  },
  {
    id: 'tool_81',
    department: Department.DISTRIBUTION,
    category: '디자인',
    tool_name: '피그마',
    description: '웹 기반 UI/UX 디자인 협업 툴',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.figma.com&sz=128',
    manual_link: '',
    service_url: 'https://www.figma.com',
    login_id: 'support@samchomaeul.com',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 81
  },
  {
    id: 'tool_82',
    department: Department.DISTRIBUTION,
    category: '미디어 소스',
    tool_name: '경리나라',
    description: '경리회계 프로그램',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.kyungrinara.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://www.kyungrinara.co.kr',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 82
  },
  {
    id: 'tool_83',
    department: Department.DISTRIBUTION,
    category: '운영관리',
    tool_name: '이지어드민',
    description: '쇼핑몰 통합 관리',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.ezadmin.co.kr&sz=128',
    manual_link: '',
    service_url: 'https://www.ezadmin.co.kr',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 83
  },
  {
    id: 'tool_84',
    department: Department.DISTRIBUTION,
    category: '생산성 AI',
    tool_name: 'Sora',
    description: '숏폼, 디자인 / 영상, 이미지 생성 AI',
    logoUrl: 'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
    manual_link: '',
    service_url: 'https://openai.com/sora',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 84
  },
  {
    id: 'tool_85',
    department: Department.DISTRIBUTION,
    category: '생산성 AI',
    tool_name: 'Kling',
    description: '숏폼, 디자인 / 영상, 이미지 생성 AI',
    logoUrl: 'https://www.google.com/s2/favicons?domain=klingai.com&sz=128',
    manual_link: '',
    service_url: 'https://klingai.com',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 85
  },
  {
    id: 'tool_86',
    department: Department.DISTRIBUTION,
    category: '생산성 AI',
    tool_name: 'Perplexity',
    description: '실시간 웹 검색 기반 AI Q&A → 신뢰할 수 있는 출처 기반 답변 제공 (AI+검색의 하이브리드)',
    logoUrl: 'https://www.google.com/s2/favicons?domain=www.perplexity.ai&sz=128',
    manual_link: '',
    service_url: 'https://www.perplexity.ai',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 86
  },
  {
    id: 'tool_87',
    department: Department.DISTRIBUTION,
    category: '생산성 AI',
    tool_name: 'Claude',
    description: '윤리성과 긴 문서 처리에 강한 AI 챗봇 → 회사 문서 요약·분석에 특화',
    logoUrl: 'https://www.google.com/s2/favicons?domain=claude.ai&sz=128',
    manual_link: '',
    service_url: 'https://claude.ai',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 87
  },
  {
    id: 'tool_88',
    department: Department.DISTRIBUTION,
    category: '생산성 AI',
    tool_name: 'Gemini',
    description: '검색 + 문서 요약 + 코드 생성 등 다양한 작업 가능',
    logoUrl: 'https://www.google.com/s2/favicons?domain=gemini.google.com&sz=128',
    manual_link: '',
    service_url: 'https://gemini.google.com',
    login_id: '',
    login_pw: '',
    memo: '',
    in_use: 'Y',
    is_paid: 'Y',
    order: 88
  }
];
